---

- name: main | Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items: [ '{{ php_fpm_main_packages }}' ]
  tags:
    - php-fpm

- name: main | Install additional packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items: [ '{{ php_fpm_additional_packages }}' ]
  notify:
    - Restart php-fpm
  tags:
    - php-fpm

- name: main | Enable service
  service:
    name: php7.0-fpm
    state: started
    enabled: yes
  tags:
    - php-fpm

- name: main | Add pools
  template:
    src: etc/php/7.0/fpm/pool.d/pool.conf.j2
    dest: "/etc/php/7.0/fpm/pool.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: [ '{{ php_fpm_pools }}' ]
  notify:
    - Restart php-fpm
  tags:
    - php-fpm
